# Generated by Django 3.1.2 on 2020-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
